spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800